apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: responsible-barnacle-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-hub/responsible-barnacle-java-springboot-gitops